package dev.atlashybrid.diagnostics;

public enum CompatibilityStatus {
    SUPPORTED,
    AVAILABLE_LATER,
    NOT_IMPLEMENTED,
    NMS_NOT_SUPPORTED,
    PAPER_API_NOT_SUPPORTED,
    MISSING_DEPENDENCY,
    DEPENDENCY_CYCLE,
    PROTECTED_NAMESPACE,
    WRONG_THREAD,
    PLUGIN_FAILURE
}
